version: "3.9"
services:
  cock-panel:
    # platform: "linux/amd64"
    container_name: cock-panel
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "3010:3000"
    image: cock-panel
    env_file: .env.docker
    depends_on:
      - postgres

  postgres:
    image: postgres
    # ports:
    #   - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready -d outline -U user"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "cock-panel"
